config/routes.rb
WriterApp::Application.routes.draw do
  resources :invitation, only: [:new, :create]
  get "home/show"

  resources :writers

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup/:id/:invitation_token', to: 'writers#new', as: :registration
  match 'admin/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/writer/dashboard/:id', to: 'writers#show'

  root :to => 'home#show'

end

app/models/writer.rb
class Writer < ActiveRecord::Base
  attr_accessible :email, :first_name, :gender, :last_name, :screen_name, :password, :password_confirmation
  has_secure_password

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :screen_name
  validates_presence_of :gender

  VALID_EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: 	{ with: VALID_EMAIL_FORMAT },
  									presence: true, uniqueness: { case_sensitive: false }

  validates :password, confirmation: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  before_save :create_remember_token
  before_save :create_invitation_token

  def save_emails(email_list)
  	email_ids = email_list.split(',')
		email_ids.each do |email|
      writer = Writer.find_by_email(email)
      if writer
        WriterMailer.invitation_mail(writer).deliver
      else
  			new_writer = Writer.new(email: email)
  			new_writer.save!(validate: false)
  			WriterMailer.invitation_mail(new_writer).deliver
      end
		end
  end

  private
  	
  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64
  	end

  	def create_invitation_token
  		self.invitation_token = SecureRandom.urlsafe_base64
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/invitation_controller.rb
class InvitationController < ApplicationController
  def new
  end

  def create
  	email_list = params[:invitation][:email_list]
  	current_writer.save_emails(email_list)
  	redirect_to root_url, notice: 'Invitation sent successfully...!!!!'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		writer = Writer.find_by_email(params[:session][:email].downcase)
		if writer && !writer.password_digest.nil?
			if writer.authenticate(params[:session][:password]) 
	      sign_in writer
	      redirect_to writer
	    else
	      flash.now[:error] = 'Invalid email/password combination'
	      render 'new'
	    end
	  else
	  	flash.now[:error] = 'Please register yourself through email invitation sent to you'
	  	render 'home/show'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  # GET /writers
  # GET /writers.json
  def index
    @writers = Writer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @writers }
    end
  end

  # GET /writers/1
  # GET /writers/1.json
  def show
    @writer = Writer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @writer }
    end
  end

  # GET /writers/new
  # GET /writers/new.json
  def new
    @writer = Writer.find(params[:id])
    if @writer.invitation_token == params[:invitation_token]
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @writer }
      end
    else
      redirect_to root_url
    end
  end

  # GET /writers/1/edit
  def edit
    @writer = Writer.find(params[:id])
  end

  # POST /writers
  # POST /writers.json
  def create
    @writer = Writer.new(params[:writer])

    respond_to do |format|
      if @writer.save
        sign_in @writer
        format.html { redirect_to @writer, notice: 'Writer successfully created.' }
        format.json { render json: @writer, status: :created, location: @writer }
      else
        format.html { render action: "new" }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /writers/1
  # PUT /writers/1.json
  def update
    @writer = Writer.find(params[:id])

    respond_to do |format|
      if @writer.update_attributes(params[:writer])
        format.html { redirect_to @writer, notice: 'Writer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1
  # DELETE /writers/1.json
  def destroy
    @writer = Writer.find(params[:id])
    @writer.destroy

    respond_to do |format|
      format.html { redirect_to writers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(writer)
    cookies.permanent[:remember_token] = writer.remember_token
    self.current_writer = writer
  end

  def signed_in?
  	!current_writer.nil?
  end

  def current_writer=(writer)
  	@current_writer = writer
  end

  def current_writer
  	@current_writer ||= Writer.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_writer = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/home/show.html.erb
<h1>Welcome to Writer's Hub</h1>
<% unless signed_in? %>
	<p><%= link_to "Sign in", admin_signin_path %> to continue</p>
<% end %>

app/views/invitation/new.html.erb
<h1>Send Invitations</h1>
<p>Enter multiple email ids by inserting comma in between them</p>

<%= form_for(:invitation, url: invitation_index_path) do |f| %>
  
	<div class="field">
		<%= f.label :email_list %><br />
  	<%= f.text_field :email_list %>
	</div>

	<%= f.submit "Invite!" %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<div class="nav_bar">
	<p>
		Signed in as :- <%= "#{current_writer.first_name} #{current_writer.last_name}" %>
		<% if current_writer.admin? %>
			(admin)
		<% end %>
	</p>
	<ul >
		<li><%=link_to 'Dashboard', writer_path(current_writer) %></li>
		<li><%=link_to 'Writers', writers_path %></li>
		<% if current_writer.admin? %>
			<li><%=link_to 'Send invitation', new_invitation_path %></li>
		<% end %>
		<li><%= link_to "Sign out", signout_path, method: :delete  %></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WriterApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if signed_in? %>
		<%= render 'layouts/nav_bar' %>
	<% end %>
	<% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
    <p><%= flash[:error] %></p>
  <% end %>
  <% if flash[:success] %>
    <p><%= flash[:success] %></p>
  <% end %>
	<%= yield %>
</body>
</html>

app/views/writers/_form.html.erb
<%= form_for(@writer) do |f| %>
  <% if @writer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@writer.errors.count, "error") %> prohibited this writer from being saved:</h2>

      <ul>
      <% @writer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :screen_name %><br />
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit "Create my account" %>
  </div>
<% end %>

app/views/writers/edit.html.erb
<h1>Editing writer</h1>

<%= render 'form' %>

<%= link_to 'Show', @writer %> |
<%= link_to 'Back', writers_path %>

app/views/writers/index.html.erb
<h1>Listing writers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Screen name</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @writers.each do |writer| %>
  <tr>
    <td><%= writer.first_name %></td>
    <td><%= writer.last_name %></td>
    <td><%= writer.email %></td>
    <td><%= writer.screen_name %></td>
    <td><%= writer.gender %></td>
    <% if current_writer.admin? && !writer.admin? %>
        <td><%= link_to 'Show', writer %></td>
        <td><%= link_to 'Edit', edit_writer_path(writer) %></td>
        <td><%= link_to 'Destroy', writer, method: :delete, data: { confirm: 'Are you sure?' } %></td>    
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Writer', new_writer_path %>

app/views/writers/new.html.erb
<h1>New writer</h1>

<%= render 'form' %>

<%= link_to 'Back', writers_path %>

app/views/writers/show.html.erb
<h1><%= "#{@writer.first_name} #{@writer.last_name}" %></h1>

<p>
  <b>Email:</b>
  <%= @writer.email %>
</p>

<p>
  <b>Screen name:</b>
  <%= @writer.screen_name %>
</p>

<p>
  <b>Gender:</b>
  <%= @writer.gender %>
</p>


<%= link_to 'Edit', edit_writer_path(@writer) %> |
<%= link_to 'Back', writers_path %>